name: belajandro_kiosk
version: 1.0.0+1
publish_to: none
description: Kiosk Application for Belajandro Hotel
environment: 
  sdk: '>=3.3.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  get_storage: ^2.1.1
  flutter: 
    sdk: flutter
  
  #INTERNATIONAL
  intl: ^0.19.0

  #COMMUNICATION
  hasura_connect: ^5.0.0+2
  http: ^1.2.1
  translator: ^1.0.0

  #RESPONSIVE 
  responsive_sizer: ^3.2.0

  #WIN32
  win32: ^5.5.0
  windows_networking: ^0.2.0
  ffi: ^2.1.2
  window_manager: ^0.3.8
  uuid: ^3.0.7

  #OTHERS
  virtual_keyboard_custom_layout: ^1.0.0
  syncfusion_flutter_datepicker: ^25.1.41

  #VISUAL EFFECTS
  flutter_animate: ^4.5.0
  dotlottie_loader: ^0.0.3
  lottie: ^3.1.0
  dropdown_search: ^5.0.6
  flutter_staggered_grid_view: ^0.7.0
  

  #IMAGING
  # camera_universal: ^0.0.3
  camera_windows: ^0.2.2


  #CUSTOM
  csharp_rpc:
    path: ./library/csharp_rpc

dev_dependencies: 
  flutter_lints: ^3.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  fonts:
    - family: "Bernard MT Condensed"
      fonts: 
        - asset: "assets/fonts/BERNHC.TTF"
    - family: 'Old Alpha'
      fonts:
        - asset: assets/fonts/OldAlpha.otf
    - family: 'DK Lemon Yellow Sun'
      fonts:
        - asset: assets/fonts/DKLemonYellowSun.otf
    - family: 'Atteron'
      fonts: 
        - asset: assets/fonts/Atteron.ttf
    - family: 'Product Sans'
      fonts: 
        - asset: assets/fonts/PRODUCT-SANS-REGULAR.ttf

  assets:
    - assets/img/
    - assets/icons/
    - assets/fonts/
    - assets/lotties/
    - assets/flags/
    - assets/rooms/
    - assets/service/bonwin/
    - assets/service/printer/