name: csharp_rpc
description: Execute C# code from Dart (Flutter) application via JSON-RPC protocol.
version: 0.0.7
maintainer: Yehuda Kremer (yehudakremer@gmail.com)
homepage: https://github.com/YehudaKremer/FlutterCsharpRpc
issue_tracker: https://github.com/YehudaKremer/FlutterCsharpRpc/issues
screenshots:
  - description: "Execute C# code from Dart (Flutter) application."
    path: doc/assets/csharp_rpc_logo_small.png

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  uuid: ^3.0.7

dev_dependencies:
  flutter_lints: ^2.0.1
